### ISSUE TITLE
Retry failed artifacts with in non-strict mode when strong cache key is not found

### ISSUE THREAD

**Issue by abderrahim** [apache/buildstream#1460] opened 2021-03-19 19:44 UTC
Building in non-strict mode, I got one usual linker error: a library bumped the version, and a library that depends on it wasn't rebuilt and I was building a  third element that depends on both. I `bst artifact delete` both libraries, disable the remote cache, and launch the build again. After building some stuff, I am presented with the exact same error.

I had a big WTF moment, before remembering that bst has cached failures. Retrying the build indeed works.

I think we shouldn't present a different build (i.e. a build with a different strict key) as the same.

**Comment by gtristan** [comment] 2022-02-17 05:24
> Building in non-strict mode, I got one usual linker error: a library bumped the version, and a library that depends on it wasn't rebuilt and I was building a third element that depends on both. 

So we're on the same page here: The above type of error is expected in `non-strict` build correct ? Because the dependency of a library was not explicitly declared as a [strict dependency](https://docs.buildstream.build/master/format_declaring.html#expressing-dependencies), and in this particular case it perhaps should have been, given that the versioning information of the library is relevant in this case and causes errors down the line at build time ?

> ... I bst artifact delete both libraries, disable the remote cache, and launch the build again. After building some stuff, I am presented with the exact same error.
>
> I had a big WTF moment, before remembering that bst has cached failures. Retrying the build indeed works.
>
> I think we shouldn't present a different build (i.e. a build with a different strict key) as the same.

But I'm a bit lost at this point as to what is going on and what happened.

Perhaps the problem is that `bst artifact delete` will only delete a single artifact, for which it has resolved the key for in the session of running `bst artifact delete` (was `--no-strict` also specified at `bst artifact delete time` ?), and does not provide any option to delete *all* locally cached artifacts for a given element ?

**Comment by abderrahim** [comment] 2022-02-21 08:47
> Because the dependency of a library was not explicitly declared as a [strict dependency](https://docs.buildstream.build/master/format_declaring.html#expressing-dependencies), and in this particular case it perhaps should have been, given that the versioning information of the library is relevant in this case and causes errors down the line at build time ?

I'd say it's not: bumping soname (that's what I meant by version) is not something that happens often, and making most dependencies strict is almost equivalent to the strict mode while being more verbose. So I guess it's something we should live with as it doesn't happen often.

> Perhaps the problem is that bst artifact delete will only delete a single artifact, for which it has resolved the key for in the session of running bst artifact delete (was --no-strict also specified at bst artifact delete time ?), and does not provide any option to delete all locally cached artifacts for a given element ?

Ok, I guess I wasn't explicit enough: I didn't delete the artifact, but I was expecting bst not to reuse it.

So I have three elements: `app1.bst`, `library1.bst` and `library2.bst`. app1 depends on library1, which depends on library2. library2 bumped its soname, and library1 was built against the old soname. I'm building app1, linking fails because library1 needs the old soname of library2 which cannot be found (*). Up to this point, everything is as expected.

I run `bst artifact delete library1.bst library2.bst` (deleting library1 only should be enough, but this is what I said above), then run the build again without the remote cache.

At this point I expect the build to succeed, building all three elements. However, what happened is that it built the two libraries and presented me with the exact same error in (*) above. It was a cached failure, and answering retry on the prompt built app1 correctly.

My point is that the second build shouldn't reuse the cached failure from the first one as they are different. So it should check the strict key rather the the weak key to determine whether to use the cached failure. I guess this would be even more problematic if it actually pulled the cached failure rather than having it already in the local cache.

**Comment by gtristan** [comment] 2022-07-19 08:56
Studying this again as it is linked from #1461

> My point is that the second build shouldn't reuse the cached failure from the first one as they are different. So it should check the strict key rather the the weak key to determine whether to use the cached failure. I guess this would be even more problematic if it actually pulled the cached failure rather than having it already in the local cache.

Finally after dancing in circles around this in my head, I think I understand and agree with your proposed behavior. I believe that you have confused the (admittedly complex/confusing) terminology of cache keys.

#### Weak cache key

The weak key takes only the element's input into consideration, disregarding dependencies

#### Strict cache key

The strict cache key is ultimately what the cache key *would be* if the element and all of it's dependencies were built in strict mode

#### Strong cache key

Also referred to simply as the *cache key*, is calculated from the element's input, and all of the dependencies against which the element *was actually built against*

### Conclusion

I think that what you are suggesting, is that:
* If the build is in non-strict mode
* If an artifact is found by it's weak key
* If the found artifact does not have the actual *strong key* which we would have assigned it
* If the found artifact is actually a failed build
* Then we should ignore the found artifact and attempt to build it again under the new *strong key*

This behavior would essentially cause failed builds to be retried in non-strict mode as long as *anything in the element or it's dependencies has changed* since the last failed build.

This would be great indeed.

However, I think we can safely rule out the relevance of this proposed enhancement with issue #1461

**Closed as completed** 2022-07-21 06:40 UTC
Labels: enhancement
